### PR TITLE
Use new claim api

### PR DESCRIPTION
**Pull request by AudioSin**

### CODE REVIEW

**Review by Mvii7 — APPROVED** [review]
Alternative is to set up proxy as done with proxy.conf.js file, but this should do

**Comment by AudioSin** [comment]
> Alternative is to set up proxy as done with proxy.conf.js file, but this should do

I didn't expect the proxy file to work with a static build. Can you try it out?

**Comment by Mvii7** [comment]
> > Alternative is to set up proxy as done with proxy.conf.js file, but this should do
> 
> I didn't expect the proxy file to work with a static build. Can you try it out?

https://angular.io/guide/build#proxying-to-a-backend-server

looks like to be done only on ng serve.. 

dunno if hardcoding this in is so nice, maybe we should pick it up from environment file instead? well we will all be using that one API, even locally, so doesnt matter really

**Comment by AudioSin** [comment]
> > > Alternative is to set up proxy as done with proxy.conf.js file, but this should do
> > 
> > 
> > I didn't expect the proxy file to work with a static build. Can you try it out?
> 
> https://angular.io/guide/build#proxying-to-a-backend-server
> 
> looks like to be done only on ng serve..
> 
> dunno if hardcoding this in is so nice, maybe we should pick it up from environment file instead? well we will all be using that one API, even locally, so doesnt matter really

Yeah you def have a point. I prefer to have it as an environment variable as well. Maybe we need to add it in the environment and prod.enviroment file for now. And later migrated it to a build process var.

**Comment by AudioSin** [comment]
@Mvii7 updated it to load it from environment file...

**Review by Vicarious1 — APPROVED** [review]
LGTM

**Pull request merged**
